name: cinebuzz_flutter
description: "A Flutter application that displays trending and now playing movies using the TMDB API, with search and bookmarking features."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  go_router: ^17.0.0
  json_annotation: ^4.9.0
  retrofit: ^4.9.1

dev_dependencies:
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  retrofit_generator: ^10.2.0

flutter:
  uses-material-design: true
